version: '3.2'
services:
  frontend:
    build: .
    image: react-microblog
    ports:
      - "80:80"
      - "443:443"
    restart: always
  api:
    build: ../microblog-api
    image: microblog-api
    volumes:
      - ../microblog-api/data:/data
    env_file: .env.api
    environment:
      DATABASE_URL: sqlite:////data/db.sqlite
    restart: always
  djangoservice:
    build: /Users/Shared/src/django_src/alex_django_db
    image: django_alex
    volumes:
        - /Users/agou/Library/Mobile Documents/com~apple~CloudDocs/Diafora:/data_django
    env_file: /Users/Shared/src/django_src/alex_django_db/.env
    restart: always
