version: '3.2'
services:
  frontend:
    build: .
    image: react-microblog
    ports:
      - "80:80"
      - "443:443"
    restart: always
  api:
    build: ../microblog-api
    image: microblog-api
    volumes:
      - ~/Library/Mobile Documents/com~apple~CloudDocs/Diafora:/data
    env_file: ../microblog-api/.env
    environment:
      DATABASE_URL: sqlite:////data/db.sqlite
    restart: always
  djangoservice:
    build: ../../django_src/alex_django_db
    image: django_alex
    volumes:
        - ~/Library/Mobile Documents/com~apple~CloudDocs/Diafora:/data_django
    env_file: ../../django_src/alex_django_db/.env
    restart: always
